### ISSUE TITLE
Map Image Source

### ISSUE THREAD

**Issue by PetraChristalbert** [kalist28/once-human-helper#1]
Hello there, i really appreciate your great work on developing once human map on android. Anyway, i want to learn to make map like that and implement coordinate system to it. So, could you please provide us more data about the map source image u are using? Because i just have another idea to make a map for my research.

thank you~~~

**Comment by kalist28** [comment]
Hi, the guide I initially got into how the tile algorithm works here -> https://github.com/p-lr/MapCompose

I took the pictures myself, I didn't make them myself from the general image, I can't tell you the software and so on.

I hope it helped you with something!
